services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pompe_api_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:16-alpine
    container_name: pompe_api_db
    environment:
      POSTGRES_DB: db_compte_pompe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "db_compte_pompe", "-U", "postgres"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data: